/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace app {
    export interface PushNotification {
        sendNotification(data: NotificationData, metadata?: Metadata): Observable<NotificationResult>;
    }
    export interface NotificationData {
        message?: string;
        code?: string;
        // json string
        payload?: string;
    }
    export interface NotificationResult {
        success?: boolean;
    }
}

